name: yt-downloader
version: '1.0'
summary: A cli written in golang to download youtube videos
description: |
  A cli written in golang to download youtube videos
  Cant download copyrighted content
confinement: strict
base: core20
parts:
  yt-downloader:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  yt-downloader:
    command: bin/yt-downloader
plugs:
  yt-downloader-network:
    interface: network
  yt-downloader-home:
    interface: home
  